project:
  type: book
  output-dir: docs
  
book:
  title: "Advanced Measurement Theory: a Computational Project-Based Approach"
  author: "William Murrah"
  
  chapters:
    - index.qmd
    - intro_R_programming.qmd
    - ctt.qmd
    - generalizability.qmd
    - factor_analysis.qmd
    - statisticalthinkinglink.qmd
  page-footer:
    left: |
      *Advanced Measurement Theory: a Computational Project-Based Approach* was written by William M. Murrah III.
    right: |
      Return to  <a href="https://www.statistical-thinking.com">statistical-thinking.com</a>.
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
